user default on >password ~* &* +@all
user centrifugo on >centrifugopass ~* &* +@all -@dangerous
user chat-service on >chat-service-pass ~* &* +@all -@dangerous
user api-gateway on >api-gateway-pass ~* &* +@all -@dangerous

appendonly no

maxmemory 256mb
maxmemory-policy allkeys-lru

save 20 1