services:
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      backend:
        condition: service_healthy
    environment:
      VITE_API_URL: http://backend:8080
    ports:
      - '5173:5173'

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "backend:8080/actuator/health/liveness" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - '8080:8080'

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_HEALTH_ENABLED: true
    healthcheck:
      test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/live' ]
      interval: 5s
      timeout: 5s
      retries: 30
    ports:
      - '9090:8080'
      - '9000:9000'
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
      - --hostname=http://localhost:9090
      - --http-enabled=true

  centrifugo:
    image: centrifugo/centrifugo:v6.1
    container_name: centrifugo
    command: centrifugo -c config.json
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    ports:
      - '8000:8000'
