include:
  - compose.infra.yaml

services:
  frontend:
    build: ./chat-frontend
    container_name: chat-frontend
    depends_on:
      api-gateway:
        condition: service_healthy
    ports:
      - '5173:5173'

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      keycloak:
        condition: service_healthy
      chat-service:
        condition: service_healthy
      centrifugo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "api-gateway:8080/actuator/health/liveness" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - '8080:8080'

  chat-service:
    build: ./chat-service
    container_name: chat-service
    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "chat-service:8080/actuator/health/liveness" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
