server:
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: chat-api-gateway
  main:
    banner-mode: off
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
        pool:
          max-idle-time: 15s
          max-life-time: 60s
      default-filters:
        - TokenRelay=
        - SaveSession=
        - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          auth-server:
            authorization-uri: ${auth-server.authorization-uri}
            token-uri: ${auth-server.token-uri}
            user-info-uri: ${auth-server.user-info-uri}
            jwk-set-uri: ${auth-server.jwk-set-uri}
            user-name-attribute: ${auth-server.user-name-attribute:sub}
        registration:
          auth-server:
            provider: auth-server
            client-id: ${auth-server.client-id}
            client-secret: ${auth-server.client-secret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
            redirect-uri: '{baseUrl}/login/oauth2/code/auth-server'

app:
  frontend-url: http://localhost:5173

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
