spring:
  data:
    redis:
      host: redis
      username: api-gateway
      password: api-gateway-pass

auth-server:
  authorization-uri: http://localhost:9090/realms/chat-dev/protocol/openid-connect/auth
  token-uri: http://keycloak:8080/realms/chat-dev/protocol/openid-connect/token
  user-info-uri: http://keycloak:8080/realms/chat-dev/protocol/openid-connect/userinfo
  jwk-set-uri: http://keycloak:8080/realms/chat-dev/protocol/openid-connect/certs
  client-id: chat-service
  client-secret: eVbKDmG46txrtU96WTIdlLk9FVZMerto

contact-service-uri: http://chat-service:8080
user-service-uri: http://chat-service:8080
message-service-uri: http://chat-service:8080
centrifugo-uri: ws://centrifugo:8000
centrifugo-proxy-uri: http://chat-service:8080

management:
  tracing.sampling.probability: 1.0
  zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans