{
 "title": "Centrifugo",
 "description": "The dashboard for monitoring Centrifugo real-messaging server - https://centrifugal.dev.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "quantile", "label": "Quantile", "query": "0.5,0.99,0.999" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({__name__=~\"centrifugo_.*\"}, instance)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(centrifugo_node_build,  version)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "Prometheus" }
  ]
 },
 "panels": [
  {
   "title": "v$version",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "![image](https://centrifugal.dev/img/favicon.png)"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(time() - process_start_time_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Instant connection stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(centrifugo_node_num_clients{instance=~\"$instance\"})",
     "legendFormat": "clients"
    },
    {
     "expr": "sum(centrifugo_node_num_users{instance=~\"$instance\"})",
     "legendFormat": "users"
    }
   ]
  },
  {
   "title": "Instant subscription/channel stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(centrifugo_node_num_subscriptions{instance=~\"$instance\"})",
     "legendFormat": "subscriptions"
    },
    {
     "expr": "sum(centrifugo_node_num_channels{instance=~\"$instance\"})",
     "legendFormat": "channels"
    }
   ]
  },
  {
   "title": "Num nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(centrifugo_node_num_nodes{instance=~\"$instance\"})",
     "legendFormat": "-"
    }
   ]
  },
  {
   "title": "Client command rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_client_command_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Client reply error rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_client_num_reply_errors{instance=~\"$instance\"}[$__rate_interval])) by (method, code)",
     "legendFormat": "{{method}}|{{code}}"
    }
   ]
  },
  {
   "title": "Client command time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(centrifugo_client_command_duration_seconds{quantile=\"$quantile\", instance=~\"$instance\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API command rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_api_command_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])) by (protocol, method)",
     "legendFormat": "{{protocol}}|{{method}}"
    }
   ]
  },
  {
   "title": "API reply error rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_api_command_errors_total{instance=~\"$instance\"}[$__rate_interval])) by (protocol, method, error)",
     "legendFormat": "{{protocol}}|{{method}}|{{error}}"
    }
   ]
  },
  {
   "title": "API command time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(centrifugo_api_command_duration_seconds{quantile=\"$quantile\", instance=~\"$instance\"}) by (protocol, method)",
     "legendFormat": "{{protocol}}|{{method}}"
    }
   ]
  },
  {
   "title": "Client connections per node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "centrifugo_node_num_clients{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unique users per node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "centrifugo_node_num_users{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Subscriptions per node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "centrifugo_node_num_subscriptions{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unique channels per node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "centrifugo_node_num_channels{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node messages sent rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_node_messages_sent_count{instance=~\"$instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Node messages received rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_node_messages_received_count{instance=~\"$instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Transport messages sent rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_transport_messages_sent{instance=~\"$instance\"}[$__rate_interval])) by (transport)",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Transport messages received rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_transport_messages_received{instance=~\"$instance\"}[$__rate_interval])) by (transport)",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Transport total messages sent rate by frame type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_transport_messages_sent{instance=~\"$instance\"}[$__rate_interval])) by (frame_type)",
     "legendFormat": "{{frame_type}}"
    }
   ]
  },
  {
   "title": "Transport total messages received rate by frame type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_transport_messages_received{instance=~\"$instance\"}[$__rate_interval])) by (frame_type)",
     "legendFormat": "{{frame_type}}"
    }
   ]
  },
  {
   "title": "Client connection rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_transport_messages_received{instance=~\"$instance\", frame_type=\"connect\"}[$__rate_interval])) by (frame_type, transport)",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Disconnect by server count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_client_num_server_disconnects{instance=~\"$instance\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Unsubscribe by server count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_client_num_server_unsubscribes{instance=~\"$instance\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Node action count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_node_action_count{instance=~\"$instance\"}[$__rate_interval])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Client connections by transport",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum(centrifugo_client_connections_inflight{instance=~\"$instance\"}) by (transport)",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "PUB/SUB lag time median",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(centrifugo_node_pub_sub_lag_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Node PUB/SUB broadcast duration median",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(centrifugo_node_broadcast_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Client ping/pong latencies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(centrifugo_client_ping_pong_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le, transport))",
     "legendFormat": "p50 {{transport}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(centrifugo_client_ping_pong_duration_seconds_bucket[$__rate_interval])) by (le, transport))",
     "legendFormat": "p95 {{transport}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(centrifugo_client_ping_pong_duration_seconds_bucket[$__rate_interval])) by (le, transport))",
     "legendFormat": "p99 {{transport}}"
    }
   ]
  },
  {
   "title": "Latest recovery success ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(rate(centrifugo_client_recover{instance=~\"$instance\",recovered=\"yes\"}[$__rate_interval]))/sum(rate(centrifugo_client_recover{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Recovery success rate"
    }
   ]
  },
  {
   "title": "Recovery success ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(rate(centrifugo_client_recover{instance=~\"$instance\", recovered=\"yes\"}[$__rate_interval]))/sum(rate(centrifugo_client_recover{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Recovery success rate"
    }
   ]
  },
  {
   "title": "Survey operation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(centrifugo_node_survey_duration_seconds{quantile=\"$quantile\", instance=~\"$instance\"}) by (op)",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Proxy calls rate by name|type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_proxy_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])) by (type, name)",
     "legendFormat": "{{name}}|{{type}}"
    }
   ]
  },
  {
   "title": "Proxy calls time by name|type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(centrifugo_proxy_duration_seconds{quantile=\"$quantile\", instance=~\"$instance\"}) by (type, name)",
     "legendFormat": "{{name}}|{{type}}"
    }
   ]
  },
  {
   "title": "Proxy call errors by name|type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_proxy_errors{instance=~\"$instance\"}[$__rate_interval])) by (type, name)",
     "legendFormat": "{{name}}|{{type}}"
    }
   ]
  },
  {
   "title": "Proxy inflight requests by name|type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_proxy_inflight_requests{instance=~\"$instance\"}[$__rate_interval])) by (type, name)",
     "legendFormat": "{{name}}|{{type}}"
    }
   ]
  },
  {
   "title": "Consumer message processed rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_consumers_messages_processed_total{instance=~\"$instance\"}[$__rate_interval])) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Consumer error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_consumers_errors_total{instance=~\"$instance\"}[$__rate_interval])) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "HTTP handler rate (requires explicit enabling)",
   "type": "timeseries",
   "description": "Enable with prometheus.instrument_http_handlers\n\nNote, due to how real-time transports implemented for non-WebSocket transport metric may be written only after long-lived connection is finished.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_node_incoming_http_requests_total{instance=~\"$instance\"}[$__rate_interval])) by (method, path, status) ",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  { "title": "Go runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Go goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Go GC duration 0.75 quantile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.75\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resident memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process OS threads created",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Redis broker PUB/SUB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "PUB/SUB app-level buffered messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 155 },
   "targets": [
    {
     "expr": "sum(centrifugo_broker_redis_pub_sub_buffered_messages{instance=~\"$instance\"}) by (pub_sub_processor, channel_type)",
     "legendFormat": "{{channel_type}}[{{pub_sub_processor}}]"
    }
   ]
  },
  {
   "title": "Dropped PUB/SUB messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 155 },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_broker_redis_pub_sub_dropped_messages{instance=~\"$instance\"}[$__rate_interval])) by (channel_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUB/SUB error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 155 },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_broker_redis_pub_sub_errors{instance=~\"$instance\"}[$__rate_interval])) by (error)",
     "legendFormat": "{{error}}"
    }
   ]
  },
  { "title": "Centrifugo PRO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 } },
  {
   "title": "Client connections by client name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "targets": [
    {
     "expr": "sum(centrifugo_client_subscriptions_inflight{instance=~\"$instance\"}) by (client_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscriptions by client name and channel namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "targets": [
    {
     "expr": "sum(centrifugo_client_subscriptions_inflight{instance=~\"$instance\"}) by (client_name, channel_namespace)",
     "legendFormat": "{{client_name}}|{{channel_namespace}}"
    }
   ]
  },
  {
   "title": "Transport messages sent by frame type and channel namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_transport_messages_sent{instance=~\"$instance\", channel_namespace!=\"\"}[$__rate_interval])) by (frame_type, channel_namespace)",
     "legendFormat": "{{frame_type}}|{{channel_namespace}}"
    }
   ]
  },
  {
   "title": "Transport messages sent size by frame type and channel namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_transport_messages_sent_size{instance=~\"$instance\", channel_namespace!=\"\"}[$__rate_interval])) by (frame_type, channel_namespace)",
     "legendFormat": "{{frame_type}}|{{channel_namespace}}"
    }
   ]
  },
  {
   "title": "Transport messages received by frame type and channel namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_transport_messages_received{instance=~\"$instance\", channel_namespace!=\"\"}[$__rate_interval])) by (frame_type, channel_namespace)",
     "legendFormat": "{{frame_type}}|{{channel_namespace}}"
    }
   ]
  },
  {
   "title": "Transport messages received size by frame type and channel namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_transport_messages_received_size{instance=~\"$instance\", channel_namespace!=\"\"}[$__rate_interval])) by (frame_type, channel_namespace)",
     "legendFormat": "{{frame_type}}|{{channel_namespace}}"
    }
   ]
  },
  {
   "title": "Client command count by channel namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_client_command_duration_seconds_count{instance=~\"$instance\", channel_namespace!=\"\"}[$__rate_interval])) by (method, channel_namespace)",
     "legendFormat": "{{method}}|{{channel_namespace}}"
    }
   ]
  },
  {
   "title": "Command duration time by channel namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(centrifugo_client_command_duration_seconds{quantile=\"$quantile\", instance=~\"$instance\", channel_namespace!=\"\"}) by (method, channel_namespace)",
     "legendFormat": "{{method}}|{{channel_namespace}}"
    }
   ]
  },
  {
   "title": "Client reply error rate by channel namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_client_num_reply_errors{instance=~\"$instance\", channel_namespace!=\"\"}[$__rate_interval])) by (method, code, channel_namespace)",
     "legendFormat": "{{method}}|{{code}}|{{channel_namespace}}"
    }
   ]
  },
  {
   "title": "Node PUB/SUB broadcast duration by channel namespace median",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(centrifugo_node_broadcast_duration_seconds_bucket{instance=~\"$instance\", channel_namespace!=\"\"}[$__rate_interval])) by (le, channel_namespace))",
     "legendFormat": "{{channel_namespace}}"
    }
   ]
  },
  {
   "title": "Recovery success ratio by channel namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  sum(rate(centrifugo_client_recover{instance=~\"$instance\", channel_namespace!=\"\", recovered=\"yes\"}[$__rate_interval])) by (channel_namespace)\n  /\n  sum(rate(centrifugo_client_recover{instance=~\"$instance\", channel_namespace!=\"\"}[$__rate_interval])) by (channel_namespace)\n)",
     "legendFormat": "{{channel_namespace}}"
    }
   ]
  },
  {
   "title": "Successful push notifications rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_push_notification_count{instance=~\"$instance\", success=\"true\"}[$__rate_interval])) by (provider, platform, recipient_type)",
     "legendFormat": "{{provider}}|{{platform}}|{{recipient_type}}"
    }
   ]
  },
  {
   "title": "Unsuccessful push notifications rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_push_notification_count{instance=~\"$instance\", success=\"false\"}[$__rate_interval])) by (provider, platform, err_code)",
     "legendFormat": "{{provider}}|{{platform}}|{{err_code}}"
    }
   ]
  },
  {
   "title": "Push notifications queue consumer lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 220 },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_push_queue_consuming_lag{instance=~\"$instance\"}[$__rate_interval])) by (provider, queue)",
     "legendFormat": "{{provider}}|{{queue}}"
    }
   ]
  },
  {
   "title": "Push notifications inflight jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 220 },
   "targets": [
    {
     "expr": "sum(centrifugo_push_consuming_inflight_jobs{instance=~\"$instance\"}) by (provider, queue)",
     "legendFormat": "{{provider}}|{{queue}}"
    }
   ]
  },
  {
   "title": "Push job rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_push_job_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])) by (provider, recipient_type)",
     "legendFormat": "{{provider}}|{{recipient_type}}"
    }
   ]
  },
  {
   "title": "Push job duration time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(centrifugo_push_job_duration_seconds{quantile=\"$quantile\", instance=~\"$instance\"}) by (provider, recipient_type)",
     "legendFormat": "{{provider}}|{{recipient_type}}"
    }
   ]
  },
  {
   "title": "Scheduled push notifications requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 236 },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_push_scheduled_request_count{instance=~\"$instance\"}[$__rate_interval])) by (recipient_type)",
     "legendFormat": "{{recipient_type}}"
    }
   ]
  }
 ]
}