spring:
  application:
    name: chat-service
  main:
    banner-mode: off
  cache:
    cache-names: users
    type: redis
    redis:
      key-prefix: 'chat:'
      time-to-live: 15m
  data:
    redis:
      client-name: chat-service
      client-type: lettuce
      connect-timeout: 1s
      timeout: 1s
      repositories:
        enabled: false
  http:
    clients:
      imperative:
        factory: http_components
      connect-timeout: 5s
      read-timeout: 5s
  liquibase:
    change-log: "classpath:db/changelog/changelog.xml"
    contexts: prod

centrifugo:
  url: http://localhost:8000
  api-key: 7bd5cf56-53bb-4710-8238-7186472819cb
  refresh-interval: 5m

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus
  tracing:
    export:
      zipkin:
        enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

