spring:
  application:
    name: chat-backend
  main:
    banner-mode: off
  cache:
    cache-names: users
    type: redis
    redis:
      key-prefix: 'chat:'
      time-to-live: 15m
  data:
    redis:
      connect-timeout: 1s
      timeout: 1s
      repositories:
        enabled: false
  datasource:
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        jdbc.batch_size: 15
        order_inserts: true
        order_updates: true
        connection.provider_disables_autocommit: true
  liquibase:
    change-log: "classpath:db/changelog/changelog.xml"
    contexts: prod

centrifugo:
  url: http://localhost:8000
  api-key: 7bd5cf56-53bb-4710-8238-7186472819cb
  connect-timeout: 1s
  read-timeout: 1s
  refresh-interval: 5m

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus
