spring:
  application:
    name: chat-backend
  main:
    banner-mode: off
  data:
    redis:
      connect-timeout: 1s
      timeout: 1s

centrifugo:
  url: http://localhost:8000
  api-key: 7bd5cf56-53bb-4710-8238-7186472819cb
  connect-timeout: 1s
  read-timeout: 1s
  refresh-interval: 5m

chat:
  messages:
    ttl: 1d

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus
