spring:
  data:
    redis:
      host: redis
      username: chat-service
      password: chat-service-pass
  datasource:
    url: jdbc:postgresql://postgres:5432/chat-service
    username: chat-service
    password: password
  liquibase:
    contexts: prod, dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/chat-dev/protocol/openid-connect/certs

centrifugo:
  url: http://centrifugo:8000
  api-key: 7bd5cf56-53bb-4710-8238-7186472819cb

logging:
  level:
    com.mikhailkarpov: debug

management:
  tracing.sampling.probability: 1.0
  zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans

