server:
  port: 8081

spring:
  data:
    redis:
      host: localhost
      username: chat-service
      password: chat-service-pass
  datasource:
    url: jdbc:postgresql://localhost:5432/chat-service
    username: chat-service
    password: password
  liquibase:
    contexts: prod, dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/chat-dev/protocol/openid-connect/certs

centrifugo:
  url: http://localhost:8000
  api-key: 7bd5cf56-53bb-4710-8238-7186472819cb

logging:
  level:
    com.mikhailkarpov: debug

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    oauth:
      client-id: chat-service
      client-secret: eVbKDmG46txrtU96WTIdlLk9FVZMerto
  oAuthFlow:
    authorizationUrl: http://localhost:9090/realms/chat-dev/protocol/openid-connect/auth
    tokenUrl: http://localhost:9090/realms/chat-dev/protocol/openid-connect/token
  cache:
    disabled: true