spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/chat-dev/protocol/openid-connect/certs

centrifugo:
  url: http://localhost:8000
  api-key: 7bd5cf56-53bb-4710-8238-7186472819cb

logging:
  level:
    com.mikhailkarpov: debug
