name: API Gateway CI

on:
  push:
    branches:
      - main
    paths:
      - 'api-gateway/**'
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    paths:
      - 'api-gateway/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test API Gateway
        run: ./gradlew :api-gateway:build

      - name: Verify test coverage
        run: ./gradlew :api-gateway:jacocoTestCoverageVerification
